--Paramètres
INSERT INTO PARAM (DBVERSION, APPREVISION, DEFAULT_LANG) VALUES (30, 1, 'fr');

--Fédérations
INSERT INTO FEDERATION VALUES ('cdf45d0f-0c69-4eb3-995a-521d4e9af5fb', 'FITA', STRINGDECODE('F\u00e9d\u00e9ration International de Tir \u00e0 l''Arc'), 'fr');
INSERT INTO FEDERATION VALUES ('4b6444ac-c9ea-45f0-a763-ba7e22db6717', 'FFTA', STRINGDECODE('F\u00e9d\u00e9ration Fran\u00e7aise de Tir \u00e0 l''Arc'), 'fr');

-- Niveau de Compétition par fédérations
INSERT INTO LIBELLE VALUES ('4e448a73-91b4-410e-828c-85b35fa180a3', 'fr', 'Qualificatif');
INSERT INTO LIBELLE VALUES ('734666f5-4e12-43e6-8ff1-636bb6bf9afa', 'fr', 'Championnat d''Europe');
INSERT INTO LIBELLE VALUES ('8c163e48-7762-4fcc-9c9d-2e84ff4c3ed6', 'fr', 'Coupe du Monde');
INSERT INTO LIBELLE VALUES ('2bb428fd-c249-40b5-ae98-54fffcbd12cf', 'fr', 'Jeux Olympique');
INSERT INTO LIBELLE VALUES ('4e448a73-91b4-410e-828c-85b35fa180a3', 'en', 'Qualifier');
INSERT INTO LIBELLE VALUES ('734666f5-4e12-43e6-8ff1-636bb6bf9afa', 'en', 'European Championship');
INSERT INTO LIBELLE VALUES ('8c163e48-7762-4fcc-9c9d-2e84ff4c3ed6', 'en', 'World Cup');
INSERT INTO LIBELLE VALUES ('2bb428fd-c249-40b5-ae98-54fffcbd12cf', 'en', 'Olympic Games');
INSERT INTO LIBELLE VALUES ('53f43e13-1b7c-4cbf-b68e-8cfc3be71897', 'fr', 'Qualificatif');
INSERT INTO LIBELLE VALUES ('01147bfa-2968-46d1-8fb6-eb79081b2c4d', 'fr', STRINGDECODE('D\u00e9partemental'));
INSERT INTO LIBELLE VALUES ('e9528958-5799-4c49-8c1c-0a9e1b3f2e3b', 'fr', STRINGDECODE('R\u00e9gional'));
INSERT INTO LIBELLE VALUES ('d921513c-14b9-4d78-b38c-7f6411d6a83b', 'fr', 'Championnat de France');
INSERT INTO LIBELLE VALUES ('96b89583-e6df-45fc-87e7-a8c3b085eca4', 'fr', 'Championnat d''Europe');
INSERT INTO LIBELLE VALUES ('6c247541-fb03-489c-929a-6648350c6699', 'fr', 'Coupe du Monde');
INSERT INTO LIBELLE VALUES ('e1ecab41-3ca5-4eba-9fdb-53a7beb7f251', 'fr', 'Jeux Olympique');

INSERT INTO NIVEAU_COMPETITION VALUES (1, 1, '4e448a73-91b4-410e-828c-85b35fa180a3', TRUE);
INSERT INTO NIVEAU_COMPETITION VALUES (2, 1, '734666f5-4e12-43e6-8ff1-636bb6bf9afa', FALSE);
INSERT INTO NIVEAU_COMPETITION VALUES (3, 1, '8c163e48-7762-4fcc-9c9d-2e84ff4c3ed6', FALSE);
INSERT INTO NIVEAU_COMPETITION VALUES (4, 1, '2bb428fd-c249-40b5-ae98-54fffcbd12cf', FALSE);
INSERT INTO NIVEAU_COMPETITION VALUES (1, 2, '53f43e13-1b7c-4cbf-b68e-8cfc3be71897', TRUE);
INSERT INTO NIVEAU_COMPETITION VALUES (2, 2, '01147bfa-2968-46d1-8fb6-eb79081b2c4d', FALSE);
INSERT INTO NIVEAU_COMPETITION VALUES (3, 2, 'e9528958-5799-4c49-8c1c-0a9e1b3f2e3b', FALSE);
INSERT INTO NIVEAU_COMPETITION VALUES (4, 2, 'd921513c-14b9-4d78-b38c-7f6411d6a83b', FALSE);
INSERT INTO NIVEAU_COMPETITION VALUES (5, 2, '96b89583-e6df-45fc-87e7-a8c3b085eca4', FALSE);
INSERT INTO NIVEAU_COMPETITION VALUES (6, 2, '6c247541-fb03-489c-929a-6648350c6699', FALSE);
INSERT INTO NIVEAU_COMPETITION VALUES (7, 2, 'e1ecab41-3ca5-4eba-9fdb-53a7beb7f251', FALSE);

--Répartition des phases finales
-- Réglement Internationnal
-- Groupe A
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(0, 1, 1);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(1, 1, 64);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(2, 1, 33);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(3, 1, 32);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(4, 1, 17);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(5, 1, 48);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(6, 1, 49);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(7, 1, 16);
--Groupe B
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(8, 1, 9);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(9, 1, 56);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(10, 1, 41);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(11, 1, 24);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(12, 1, 25);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(13, 1, 40);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(14, 1, 57);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(15, 1, 8);
--Groupe C
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(16, 1, 5);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(17, 1, 60);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(18, 1, 37);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(19, 1, 28);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(20, 1, 21);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(21, 1, 44);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(22, 1, 53);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(23, 1, 12);
-- Groupe D
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(24, 1, 13);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(25, 1, 52);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(26, 1, 45);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(27, 1, 20);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(28, 1, 29);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(29, 1, 36);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(30, 1, 61);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(31, 1, 4);
-- Groupe E
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(32, 1, 3);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(33, 1, 62);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(34, 1, 35);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(35, 1, 30);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(36, 1, 19);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(37, 1, 46);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(38, 1, 51);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(39, 1, 14);
--Groupe F
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(40, 1, 11);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(41, 1, 54);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(42, 1, 43);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(43, 1, 22);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(44, 1, 27);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(45, 1, 38);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(46, 1, 59);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(47, 1, 6);
-- Groupe G
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(48, 1, 7);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(49, 1, 58);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(50, 1, 39);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(51, 1, 26);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(52, 1, 23);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(53, 1, 42);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(54, 1, 55);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(55, 1, 10);
-- Groupe H
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(56, 1, 15);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(57, 1, 50);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(58, 1, 47);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(59, 1, 18);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(60, 1, 31);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(61, 1, 34);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(62, 1, 63);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(63, 1, 2);

-- Réglement Français
-- Groupe A
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(0, 2, 44);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(1, 2, 21);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(2, 2, 53);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(3, 2, 12);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(4, 2, 37);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(5, 2, 28);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(6, 2, 60);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(7, 2, 5);
--Groupe B
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(8, 2, 45);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(9, 2, 20);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(10, 2, 52);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(11, 2, 13);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(12, 2, 36);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(13, 2, 29);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(14, 2, 61);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(15, 2, 4);
--Groupe C
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(16, 2, 41);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(17, 2, 24);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(18, 2, 56);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(19, 2, 9);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(20, 2, 40);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(21, 2, 25);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(22, 2, 57);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(23, 2, 8);
-- Groupe D
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(24, 2, 48);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(25, 2, 17);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(26, 2, 49);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(27, 2, 16);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(28, 2, 33);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(29, 2, 32);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(30, 2, 64);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(31, 2, 1);
-- Groupe E
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(32, 2, 2);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(33, 2, 63);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(34, 2, 31);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(35, 2, 34);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(36, 2, 15);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(37, 2, 50);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(38, 2, 18);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(39, 2, 47);
--Groupe F
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(40, 2, 7);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(41, 2, 58);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(42, 2, 26);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(43, 2, 39);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(44, 2, 10);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(45, 2, 55);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(46, 2, 23);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(47, 2, 42);
-- Groupe G
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(48, 2, 3);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(49, 2, 62);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(50, 2, 30);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(51, 2, 35);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(52, 2, 14);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(53, 2, 51);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(54, 2, 19);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(55, 2, 46);
-- Groupe H
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(56, 2, 6);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(57, 2, 59);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(58, 2, 27);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(59, 2, 38);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(60, 2, 11);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(61, 2, 54);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(62, 2, 22);
INSERT INTO REPARTITION_PHASE_FINALE (NUM_REPARTITION_PHASE_FINALE, NUM_TYPE_REPARTITION, NUM_ORDRE) VALUES(63, 2, 43);

-- Type Equipe
INSERT INTO TYPE_EQUIPE VALUES ('D1', 2, 'fr', 'Division 1');
INSERT INTO TYPE_EQUIPE VALUES ('D2', 2, 'fr', 'Division 2');
INSERT INTO TYPE_EQUIPE VALUES ('DR', 2, 'fr', STRINGDECODE('Division R\u00e9gional'));
INSERT INTO TYPE_EQUIPE VALUES ('DNAP', 2, 'fr', STRINGDECODE('Division National Arc \u00e0 Poulies'));
INSERT INTO TYPE_EQUIPE VALUES ('DE', 2, 'fr', STRINGDECODE('Duel Equipe'));
INSERT INTO TYPE_EQUIPE VALUES ('LIBRE', 2, 'fr', '');

--Catégorie de Réglement
INSERT INTO CATEGORIE_REGLEMENT VALUES (1, 'Jeunes');
INSERT INTO CATEGORIE_REGLEMENT VALUES (2, 'Salle');
INSERT INTO CATEGORIE_REGLEMENT VALUES (3, STRINGDECODE('Ext\u00e9rieur'));
INSERT INTO CATEGORIE_REGLEMENT VALUES (4, 'Autre');

--Blasons
INSERT INTO BLASONS VALUES (1, '122cm', 1, 1, 4, 122, 'targetface_fita_122.png');
INSERT INTO BLASONS VALUES (2, '80cm', 1, 1, 4, 80, 'targetface_fita_80.png');
INSERT INTO BLASONS VALUES (3, '60cm', 0.5, 1, 2, 60, 'targetface_fita_60.png');
INSERT INTO BLASONS VALUES (4, '40cm', 0.5, 0.5, 1, 40, 'targetface_fita_40.png');
INSERT INTO BLASONS VALUES (5, 'Tri Spot "Vegas"', 0.5, 0.5, 1, 39, 'targetface_fita_trispot_vegas.png');
INSERT INTO BLASONS VALUES (6, 'Tri Spot Vertical', 0.25, 1, 1, 24, 'targetface_fita_trispot.png');
INSERT INTO BLASONS VALUES (7, 'Tri Spot 60 Vertical', 0.25, 1, 1, 59, 'targetface_fita_trispot_60.png');
INSERT INTO BLASONS VALUES (8, 'Carte Beursault (Championnats)', 1, 1, 4, 23, 'targetface_ffta_beursault.png');
INSERT INTO BLASONS VALUES (9, 'Carte Beursault (Bouquet)', 1, 1, 4, 23, 'targetface_ffta_beursault_bouquet.png');
INSERT INTO BLASONS VALUES (10, '80cm Réduit (5-10)', 0.5, 0.5, 1, 79, 'targetface_fita_80_reducted.png');

-- Emplacement:
-- 0 à 3 postion A, B, C, D
-- 4 les 4 à la fois, 5 AC, 6 BD
INSERT INTO ANCRAGES_BLASONS VALUES (1, 4, 0, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (2, 4, 0, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (3, 5, 0, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (3, 6, 0.5, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (4, 0, 0, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (4, 1, 0.5, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (4, 2, 0, 0.5);
INSERT INTO ANCRAGES_BLASONS VALUES (4, 3, 0.5, 0.5);
INSERT INTO ANCRAGES_BLASONS VALUES (5, 0, 0, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (5, 1, 0.5, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (5, 2, 0, 0.5);
INSERT INTO ANCRAGES_BLASONS VALUES (5, 3, 0.5, 0.5);
INSERT INTO ANCRAGES_BLASONS VALUES (6, 0, 0, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (6, 1, 0.5, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (6, 2, 0.25, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (6, 3, 0.75, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (7, 0, 0, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (7, 1, 0.5, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (7, 2, 0.25, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (7, 3, 0.75, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (8, 4, 0, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (9, 4, 0, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (10, 0, 0, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (10, 1, 0.5, 0);
INSERT INTO ANCRAGES_BLASONS VALUES (10, 2, 0, 0.5);
INSERT INTO ANCRAGES_BLASONS VALUES (10, 3, 0.5, 0.5);

INSERT INTO CIVILITY (ABREVIATION,LIBELLE,MORALE) VALUES ('M.', 'Monsieur', 0);
INSERT INTO CIVILITY (ABREVIATION,LIBELLE,MORALE) VALUES ('Mme', 'Madame', 0);
INSERT INTO CIVILITY (ABREVIATION,LIBELLE,MORALE) VALUES ('Mlle', 'Mademoiselle', 0);
INSERT INTO CIVILITY (ABREVIATION,LIBELLE,MORALE) VALUES ('Dr.', 'Docteur', 0);
INSERT INTO CIVILITY (ABREVIATION,LIBELLE,MORALE) VALUES ('Me', 'Maître', 0);

SET @NEW_UUID = RANDOM_UUID();
INSERT INTO LIBELLE VALUES (@NEW_UUID,'fr','Archer(e)');
INSERT INTO LIBELLE VALUES (@NEW_UUID,'en','Bowman');
INSERT INTO CATEGORIE_CONTACT (NUM_CATEGORIE_CONTACT,ID_LIBELLE) VALUES (1,@NEW_UUID);
SET @NEW_UUID = RANDOM_UUID();
INSERT INTO LIBELLE VALUES (@NEW_UUID,'fr','Président(e)');
INSERT INTO LIBELLE VALUES (@NEW_UUID,'en','President');
INSERT INTO CATEGORIE_CONTACT (NUM_CATEGORIE_CONTACT,ID_LIBELLE) VALUES (2,@NEW_UUID);
SET @NEW_UUID = RANDOM_UUID();
INSERT INTO LIBELLE VALUES (@NEW_UUID,'fr','Secrétaire');
INSERT INTO LIBELLE VALUES (@NEW_UUID,'en','Secretary');
INSERT INTO CATEGORIE_CONTACT (NUM_CATEGORIE_CONTACT,ID_LIBELLE) VALUES (3,@NEW_UUID);
SET @NEW_UUID = RANDOM_UUID();
INSERT INTO LIBELLE VALUES (@NEW_UUID,'fr','Trésorier(e)');
INSERT INTO LIBELLE VALUES (@NEW_UUID,'en','Treasurer');
INSERT INTO CATEGORIE_CONTACT (NUM_CATEGORIE_CONTACT,ID_LIBELLE) VALUES (4,@NEW_UUID);
SET @NEW_UUID = RANDOM_UUID();
INSERT INTO LIBELLE VALUES (@NEW_UUID,'fr','Résponsable Inscription');
INSERT INTO LIBELLE VALUES (@NEW_UUID,'en','Registration Manager');
INSERT INTO CATEGORIE_CONTACT (NUM_CATEGORIE_CONTACT,ID_LIBELLE) VALUES (5,@NEW_UUID);
SET @NEW_UUID = RANDOM_UUID();
INSERT INTO LIBELLE VALUES (@NEW_UUID,'fr','Divers');
INSERT INTO LIBELLE VALUES (@NEW_UUID,'en','Diverse');
INSERT INTO CATEGORIE_CONTACT (NUM_CATEGORIE_CONTACT,ID_LIBELLE) VALUES (6,@NEW_UUID);

INSERT INTO CATEGORIE_REGLEMENT (NUMCATEGORIE_REGLEMENT, NOMCATEGORIE) VALUES (1, 'Salle');
INSERT INTO CATEGORIE_REGLEMENT (NUMCATEGORIE_REGLEMENT, NOMCATEGORIE) VALUES (2, 'Exterieur');
INSERT INTO CATEGORIE_REGLEMENT (NUMCATEGORIE_REGLEMENT, NOMCATEGORIE) VALUES (3, 'Jeunes');
INSERT INTO CATEGORIE_REGLEMENT (NUMCATEGORIE_REGLEMENT, NOMCATEGORIE) VALUES (4, 'Autres');