CREATE LOCAL TEMPORARY TABLE TEMP_NIVEAU_COMPETITION_LIBELLE_ID AS
	SELECT RANDOM_UUID() AS ID_LIBELLE, CODENIVEAU, NUMFEDERATION FROM (SELECT DISTINCT CODENIVEAU,NUMFEDERATION FROM NIVEAU_COMPETITION) AS A;

--Création des libellé
INSERT INTO LIBELLE (ID_LIBELLE, LANG, LIBELLE)
	SELECT ID_LIBELLE,LANG,LIBELLE
		FROM NIVEAU_COMPETITION NC
			INNER JOIN TEMP_NIVEAU_COMPETITION_LIBELLE_ID TNCLID ON TNCLID.CODENIVEAU=NC.CODENIVEAU AND TNCLID.NUMFEDERATION=NC.NUMFEDERATION;
			
ALTER TABLE NIVEAU_COMPETITION ADD ID_LIBELLE UUID;
UPDATE NIVEAU_COMPETITION UNC SET ID_LIBELLE = (SELECT TNCLID.ID_LIBELLE
	FROM NIVEAU_COMPETITION NC
		INNER JOIN TEMP_NIVEAU_COMPETITION_LIBELLE_ID TNCLID
			ON NC.CODENIVEAU=TNCLID.CODENIVEAU AND NC.NUMFEDERATION=TNCLID.NUMFEDERATION
	WHERE NC.CODENIVEAU=UNC.CODENIVEAU AND NC.NUMFEDERATION=UNC.NUMFEDERATION AND NC.LANG=UNC.LANG);
--Suppression des doublons
CREATE LOCAL TEMPORARY TABLE T_NIVEAU_COMPETITION AS SELECT ROWNUM() as UID,* FROM NIVEAU_COMPETITION;

UPDATE NIVEAU_COMPETITION AS UNC SET LIBELLE=(select B.LIBELLE from NIVEAU_COMPETITION NC
	LEFT JOIN (
		SELECT TNC.* FROM T_NIVEAU_COMPETITION TNC
			INNER JOIN (SELECT MIN(UID) AS MIN_UID, NUMFEDERATION, CODENIVEAU
				FROM T_NIVEAU_COMPETITION GROUP BY NUMFEDERATION, CODENIVEAU) A ON A.MIN_UID=TNC.UID) B
		ON B.CODENIVEAU=NC.CODENIVEAU AND B.NUMFEDERATION=NC.NUMFEDERATION AND B.LANG=NC.LANG
	WHERE NC.CODENIVEAU=UNC.CODENIVEAU AND NC.NUMFEDERATION=UNC.NUMFEDERATION AND NC.LANG=UNC.LANG);
DELETE FROM NIVEAU_COMPETITION WHERE LIBELLE IS NULL;

DROP TABLE T_NIVEAU_COMPETITION;
DROP TABLE TEMP_NIVEAU_COMPETITION_LIBELLE_ID;

--ALTER TABLE NIVEAU_COMPETITION ADD FOREIGN KEY (ID_LIBELLE) REFERENCES LIBELLE (ID_LIBELLE) ON UPDATE CASCADE ON DELETE CASCADE;