name: ConcoursJeunes CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - if: ${{ env.ACT }}
      name: Hack container for local development
      run: |
          curl -SLO https://deb.nodesource.com/nsolid_setup_deb.sh
          chmod 500 nsolid_setup_deb.sh
          ./nsolid_setup_deb.sh 20
          apt-get install nodejs -y

    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
      env:
        RUNNER_TEMP: /tmp

    - name: Install packages
      run: |
        sudo mkdir -p /usr/share/man/man1
        sudo apt-get update
        sudo apt-get -y install ant ivy fakeroot rpm nsis genisoimage dpkg-dev debhelper build-essential

    - name: Download resources
      run: ant -f projectBuilder.xml buildgenaratedressources
    
    - name: Build
      run: ant -f build.xml ivy resolve all-system

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: setup artifacts
        path: |
          pack/linux/*.tar.gz
          pack/linux/rpm/RPMS/noarch/*.rpm
          pack/linux/deb/*.deb
          pack/windows/setup*.exe
      