name: ConcoursJeunes CI build

on:
  push:
    branches: [ 2.3 ]
  pull_request:
    branches: [ 2.3 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - if: ${{ env.ACT }}
      name: Hack container for local development
      run: |
          curl -SLO https://deb.nodesource.com/nsolid_setup_deb.sh
          chmod 500 nsolid_setup_deb.sh
          ./nsolid_setup_deb.sh 20
          apt-get install nodejs -y

    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
      env:
        RUNNER_TEMP: /tmp

    - name: Install packages
      run: |
        sudo mkdir -p /usr/share/man/man1
        sudo apt-get update
        sudo apt-get -y install ant fakeroot rpm nsis genisoimage dpkg-dev debhelper build-essential

    - name: Get Secrets
      env:
        SIGN_KEYSTORE: ${{secrets.SIGN_KEYSTORE}}
        SIGN_PROJECT_PROPERTIES: ${{secrets.SIGN_PROJECT_PROPERTIES}}
        FFTA_AES_KEY: ${{secrets.FFTA_AES_KEY}}
      run: |
        echo "$SIGN_PROJECT_PROPERTIES" | base64 --decode > packager/security.properties
        echo "$SIGN_KEYSTORE" | base64 --decode > packager/signingkeys.jks
        echo "$FFTA_AES_KEY" > packager/ffta.key

    - name: Download resources
      run: ant -f projectBuilder.xml buildgenaratedressources
    
    - name: Build
      run: ant -f build.xml all-system dev_doc

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: setup artifacts
        path: |
          pack/linux/*.tar.gz
          pack/linux/rpm/RPMS/noarch/*.rpm
          pack/linux/deb/*.deb
          pack/windows/setup*.exe
      