name: ConcoursJeunes CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Download resources
      run: ant -f projectBuilder.xml buildgenaratedressources
    
    - name: Build
      run: ant -f build.xml all-system dev_doc
      
    - name: Publish
      run: ant -f build.xml publish